source 'https://github.com/xiaoxu-rc/MultiSDKSpec.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'ChatRoomSDK_Example' do
  pod 'ChatRoomSDK', :path => '../'
  
end
