use_frameworks!

platform :ios, '10.0'

target 'ChatRoomSDK_Example' do
  pod 'ChatRoomSDK', :path => '../'
  pod 'IMLibCore', :path => '../../IMLibCore'

  target 'ChatRoomSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
